### ISSUE TITLE
Property definition value cannot be null.

### ISSUE THREAD

**Issue by citrizon** [tabaneproject/ecmagen#4]
PropertyDefinition node's value property can have null value but the code generator throws an error when a null value supplied.
Example Code:
```js
class Hey {
    hoo;
}
```
output:
```
~/Documents/Repositories/tabane/node_modules/@tabaneproject/ecmagen/escodegen.js:2594
        type = expr.type || Syntax.Property;
                    ^

TypeError: Cannot read properties of null (reading 'type')
    at CodeGenerator.generateExpression (~/Documents/Repositories/tabane/node_modules/@tabaneproject/ecmagen/escodegen.js:2594:21)
    at CodeGenerator.generateAssignment (~/Documents/Repositories/tabane/node_modules/@tabaneproject/ecmagen/escodegen.js:1060:22)
    at CodeGenerator.PropertyDefinition (~/Documents/Repositories/tabane/node_modules/@tabaneproject/ecmagen/escodegen.js:1185:30)
    at CodeGenerator.generateExpression (~/Documents/Repositories/tabane/node_modules/@tabaneproject/ecmagen/escodegen.js:2601:28)
```

**Comment by citrizon** [comment]
fixed in https://github.com/tabaneproject/ecmagen/commit/13699f20a45b88ecdf1d8f13f81769614be23a30
